name: agrigrow
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.5+1
  google_fonts: ^7.0.0
  dio: ^5.9.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true

  image_path: assets/images/argo-grow.png

  adaptive_icon_background: "#426F4C"
  adaptive_icon_foreground: assets/images/argo-grow.png

flutter_native_splash:
  color: "#426F4C" # background color of splash
  image: assets/images/argo-grow.png # centered splash image
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
  web: false
