name: agrigrow
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.5+1
  google_fonts: ^7.0.0
  dio: ^5.9.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  fl_chart: ^1.1.1
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.0

flutter_launcher_icons:
  android: true
  ios: true

  image_path: assets/images/argo-grow.png

  adaptive_icon_background: "#426F4C"
  adaptive_icon_foreground: assets/images/argo-grow.png

flutter_native_splash:
  color: "#426F4C"
  image: assets/images/argo-grow.png

  android: true
  ios: true
  web: false

  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true

  android_12:
    image: assets/images/argo-grow.png
    icon_background_color: "#426F4C"
    image_dark: assets/images/argo-grow.png
    icon_background_color_dark: "#426F4C"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
